version: '3.3'
services:
  db:
    image: mysql:latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin